version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: kdsuf_postgres
    restart: always
    environment:
      POSTGRES_DB: kdsuf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
